#!/bin/sh
[ -n "$IPKG_INSTROOT" ] && exit 0
if [ -f /etc/uci-defaults/95-materialluci ]; then
    /bin/sh /etc/uci-defaults/95-materialluci || exit $?
    rm -f /etc/uci-defaults/95-materialluci
fi
rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache
exit 0
